// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { execSync } from "node:child_process";
import { defineConfig } from "prisma/config";

function resolveDatabaseUrl() {
  if (process.env["DATABASE_URL"]) {
    return process.env["DATABASE_URL"];
  }

  try {
    return execSync(
      "/opt/elasticbeanstalk/bin/get-config environment -k DATABASE_URL",
      { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }
    ).trim();
  } catch {
    return undefined;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
});
